[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "football_tactical_ai"
version = "0.1.0"
description = "RL football environments"
requires-python = ">=3.10"
dependencies = [
  "matplotlib>=3.7",
  "numpy>=1.25",
  "pandas>=2.1",
  "scikit-learn>=1.3",
  "scipy>=1.11",
  "torch>=2.0",
  "torchvision>=0.15",
  "gymnasium>=0.29"
]

[tool.setuptools.packages.find]
where = ["src"]